[contentStyle]
x = #paddingOuter#
y = #paddingOuter#
fontFace = #font#
fontSize = (16 * #scale#)
fontColor = #color#
solidColor = #background#
padding = #paddingInner#, #paddingInner#, #paddingInner#, #paddingInner#
antiAlias = 1

[contentStyle2]
y = #paddingOuter#
fontFace = #font#
fontSize = (16 * #scale#)
fontColor = #color2#
solidColor = #background2#
padding = #paddingInner#, #paddingInner#, #paddingInner#, #paddingInner#
dynamicVariables = 1
antiAlias = 1

[icontentStyle]
x = #paddingOuter#
y = #paddingOuter#
fontFace = #font#
fontSize = (16 * #scale#)
fontColor = #color2#
solidColor = #background2#
padding = #paddingInner#, #paddingInner#, #paddingInner#, #paddingInner#
antiAlias = 1

[icontentStyle2]
y = #paddingOuter#
fontFace = #font#
fontSize = (16 * #scale#)
fontColor = #color#
solidColor = #background#
padding = #paddingInner#, #paddingInner#, #paddingInner#, #paddingInner#
dynamicVariables = 1
antiAlias = 1
