[tabStyle]
w = 150
h = 30
x = 150r
y = 15
stringAlign = centerCenter
stringCase = #fontCasing#
fontFace = #font#
fontSize = (14 * #scale#)
fontColor = #color#
solidColor = #background#
antiAlias = 1

[tabSelectedStyle]
fontColor = #color2#
solidColor = #background2#

[textHeaderStyle]
x = 30
y = 60
inlineSetting = underline
stringCase = #fontCasing#
stringStyle = italic
fontFace = #font#
fontSize = (32 * #scale#)
fontColor = #color2#
antiAlias = 1
