[variables]

; colors

background = 0, 0, 0, 100
;background2 = 15, 15, 15
background2 = 220, 220, 220
color = 200, 200, 200
;color2 = 250, 250, 250
color2 = 0, 0, 0

; size

paddingInner = 16
paddingOuter = 16
scale = 1
consoleScale = 0.7

; style

font = roboto
fontCasing = lower

; player, enter a player from https://docs.rainmeter.net/manual/measures/nowplaying/#playerlist
player = cad

; position, set to 1 to automatically position console
automove = 1

; weather, leave location code as 0 to automatically get location
locationCode = 0


; launcher


launcher1name = Notepad
launcher1path = notepad

launcher2name = Command Prompt
launcher2path = cmd

launcher3name = Paint
launcher3path = mspaint

launcher4name = Notepad
launcher4path = notepad

launcher5name = Command Prompt
launcher5path = cmd

launcher6name = Paint
launcher6path = mspaint
