[variables]

; colors

background = 0, 0, 0, 100
background2 = 15, 15, 15
;background2 = 220, 220, 220
color = 200, 200, 200
color2 = 250, 250, 250
;color2 = 0, 0, 0

; size

paddingInner = 16
paddingOuter = 16
scale = 1
consoleScale = 0.7

; style

font = roboto
fontCasing = lower

; player, enter a player from https://docs.rainmeter.net/manual/measures/nowplaying/#playerlist
player = cad

; position, set to 1 to automatically position console
automove = 1

; weather, leave location code as 0 to automatically get location
locationCode = 0


; launcher


launcher1name = Hyper Terminal
launcher1path = ""C:\\Users\\M1n1n-\\AppData\\local\\hyper\\hyper.exe""

launcher2name = Visual Studio Code
launcher2path = ""F:\\Program Files (x86)\\Microsoft VS Code\\Code.exe""

launcher3name = Visual Studio
launcher3path = ""F:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Common7\\IDE\\devenv.exe""

launcher4name = Notepad++
launcher4path = ""F:\\Program Files (x86)\\Notepad++\\Notepad++.exe""

launcher5name = Paint
launcher5path = ""mspaint""

launcher6name = Games
launcher6path = ""F:\\Stuff\\Games""
