[variables]

; colors

background = 0, 0, 0, 100
background2 = 15, 15, 15
;background2 = 200, 200, 200
color = 200, 200, 200
color2 = 250, 250, 250
;color2 = 0, 0, 0

; size

paddingInner = 16
paddingOuter = 16
scale = 1
consoleScale = 0.8

; style

font = roboto
fontCasing = lower

; position, set to 1 to automatically position console
automove = 1

; weather, leave location code as 0 to automatically get location
locationCode = 0
